name: gewuerze als werbegeschenk
favicon: null
layout_spectrum: 0.10534024937078357
typography_spectrum: 0.8479416684713215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2708482099696994
  lightness: 0.3598101516254246
  saturation: 0.7419692853000015
  rhythmicContrast: 0.9101506546139717
purpose: []
